<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EmployeesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('employees')->delete();
        
        \DB::table('employees')->insert(array (
            0 => 
            array (
                'id' => 1,
                'photo' => 'photo/23657442-XU2R.jpg',
                'employee_no' => '001',
                'last_name' => 'Damayo',
                'first_name' => 'Winnie',
                'middle_name' => 'Alterado',
                'tin' => NULL,
                'sss' => NULL,
                'pagibig' => NULL,
                'philhealth' => NULL,
                'home_address' => 'Near EVRMC hospital',
                'current_address' => 'Cabungahan Villaba Leyte',
                'house_no' => NULL,
                'street' => NULL,
                'barangay' => NULL,
                'city' => 'Ormoc',
                'province' => 'Leyte',
                'zip_code' => '6537',
                'gender_id' => 1,
                'birth_date' => NULL,
                'birth_place' => NULL,
                'civil_status_id' => 1,
                'date_of_marriage' => NULL,
                'telephone_no' => NULL,
                'mobile_no' => '09208783268',
                'personal_email' => 'winnie131212592@gmail.com',
                'company_email' => 'winnie131212592@gmail.com',
                'created_at' => '2025-03-21 13:43:41',
                'updated_at' => '2025-03-26 19:06:16',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'photo' => 'photo/images-1-6Ndo.jpg',
                'employee_no' => '002',
                'last_name' => 'Cline',
                'first_name' => 'Aurora',
                'middle_name' => 'Ava Dalton',
                'tin' => NULL,
                'sss' => NULL,
                'pagibig' => NULL,
                'philhealth' => NULL,
                'home_address' => 'Quia sapiente pariat',
                'current_address' => 'Autem corporis proid',
                'house_no' => 'Aliquid eaque sit li',
                'street' => 'Unde assumenda quia',
                'barangay' => NULL,
                'city' => 'Ut laboris in lorem',
                'province' => 'Reiciendis harum acc',
                'zip_code' => '64310',
                'gender_id' => 1,
                'birth_date' => '1972-10-21',
                'birth_place' => 'Iure est consectetur',
                'civil_status_id' => 2,
                'date_of_marriage' => '1972-01-26',
            'telephone_no' => '+1 (603) 463-4688',
                'mobile_no' => NULL,
                'personal_email' => 'jixo@mailinator.com',
                'company_email' => 'pypob@mailinator.com',
                'created_at' => '2025-03-21 17:24:06',
                'updated_at' => '2025-03-26 19:06:39',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'photo' => 'photo/download-TjNV.jpg',
                'employee_no' => '003',
                'last_name' => 'Hansen',
                'first_name' => 'Seth',
                'middle_name' => 'Tatyana',
                'tin' => NULL,
                'sss' => NULL,
                'pagibig' => NULL,
                'philhealth' => NULL,
                'home_address' => 'Enim ut velit ab rec',
                'current_address' => 'Ab aliquip elit adi',
                'house_no' => 'Sunt et ipsam nemo v',
                'street' => 'Minim esse placeat',
                'barangay' => NULL,
                'city' => 'Velit maiores magni',
                'province' => 'Vel velit facere des',
                'zip_code' => '17616',
                'gender_id' => 2,
                'birth_date' => '1985-03-16',
                'birth_place' => 'Voluptas quo omnis o',
                'civil_status_id' => 4,
                'date_of_marriage' => '1994-11-21',
            'telephone_no' => '+1 (492) 872-7979',
                'mobile_no' => NULL,
                'personal_email' => 'ramoni@mailinator.com',
                'company_email' => 'dulavyjum@mailinator.com',
                'created_at' => '2025-03-21 17:25:09',
                'updated_at' => '2025-03-26 19:06:49',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'photo' => 'photo/images-3-3a5W.jpg',
                'employee_no' => '004',
                'last_name' => 'Barrera',
                'first_name' => 'Wallace',
                'middle_name' => 'Renee Hull',
                'tin' => NULL,
                'sss' => NULL,
                'pagibig' => NULL,
                'philhealth' => NULL,
                'home_address' => 'Non ullamco quisquam',
                'current_address' => 'Consequatur Tenetur',
                'house_no' => 'Non id possimus con',
                'street' => 'Dolor quisquam in do',
                'barangay' => NULL,
                'city' => 'Aut illo odit dolor',
                'province' => 'Id rem harum culpa',
                'zip_code' => '74048',
                'gender_id' => 2,
                'birth_date' => '2017-01-14',
                'birth_place' => 'Expedita similique f',
                'civil_status_id' => 1,
                'date_of_marriage' => '1987-08-05',
            'telephone_no' => '+1 (508) 819-2994',
                'mobile_no' => NULL,
                'personal_email' => 'rudebyje@mailinator.com',
                'company_email' => 'cedol@mailinator.com',
                'created_at' => '2025-03-21 17:25:51',
                'updated_at' => '2025-03-26 19:07:01',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'photo' => 'photo/images-2-rPwo.jpg',
                'employee_no' => '005',
                'last_name' => 'Sawyer',
                'first_name' => 'Susan',
                'middle_name' => 'Maryam Horton',
                'tin' => '005224434',
                'sss' => '00511223334',
                'pagibig' => '005005656',
                'philhealth' => '005000434',
                'home_address' => 'Accusamus reprehende',
                'current_address' => 'Qui cupidatat in rep',
                'house_no' => 'Non laborum laborios',
                'street' => 'Nostrud ipsum qui do',
                'barangay' => NULL,
                'city' => 'Facilis deserunt et',
                'province' => 'Quia aliquid et aute',
                'zip_code' => '70140',
                'gender_id' => 2,
                'birth_date' => '2023-08-13',
                'birth_place' => 'Dolore quidem libero',
                'civil_status_id' => 2,
                'date_of_marriage' => '2005-08-25',
            'telephone_no' => '+1 (663) 925-9094',
                'mobile_no' => NULL,
                'personal_email' => 'lasywe@mailinator.com',
                'company_email' => 'jykepy@mailinator.com',
                'created_at' => '2025-03-26 19:03:08',
                'updated_at' => '2025-03-26 19:03:08',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}